# Generated by Django 4.2.3 on 2023-08-14 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingsetting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='time',
            field=models.TimeField(default=datetime.time(11, 42, 22, 515293), verbose_name='время рассылки'),
        ),
    ]
