# Generated by Django 4.2.3 on 2023-08-14 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsetting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 14, 11, 44, 44, 296011), verbose_name='время рассылки'),
        ),
    ]
