# Generated by Django 4.2.3 on 2023-08-15 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingsetting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 15, 15, 20, 11, 742980, tzinfo=datetime.timezone.utc), verbose_name='время рассылки'),
        ),
    ]
