# Generated by Django 4.2.3 on 2023-08-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailingsetting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='time',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='dateend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 27, 14, 25, 40, 94711, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='datestart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 20, 14, 25, 40, 94696, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата начала'),
        ),
    ]
