# Generated by Django 4.2.3 on 2023-08-23 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0006_remove_mailingsetting_time_mailingsetting_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='dateend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 19, 39, 22, 756701, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='datestart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 19, 39, 22, 756684, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата начала'),
        ),
    ]
