# Generated by Django 4.2.3 on 2023-08-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailingsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='dateend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 11, 26, 22, 90519, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='datestart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 11, 26, 22, 90504, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата начала'),
        ),
    ]
