# Generated by Django 4.2.3 on 2023-08-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_shape_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ('name_shape',), 'verbose_name': 'форма проудкта', 'verbose_name_plural': 'форрмы продуктов'},
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт'),
        ),
    ]
