# Generated by Django 4.2.3 on 2023-08-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ('name_shape',), 'verbose_name': 'форма проудкта', 'verbose_name_plural': 'формы продуктов'},
        ),
    ]
