# Generated by Django 4.2.3 on 2023-08-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_shape_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='доступно для продажи'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name_version',
            field=models.CharField(max_length=150, verbose_name='назание'),
        ),
    ]
